# Generated by Django 3.1.2 on 2020-10-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201025_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability_level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='number_of_places',
            field=models.PositiveIntegerField(),
        ),
    ]
