# Generated by Django 3.1.2 on 2020-10-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201025_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
