# Generated by Django 3.1.2 on 2020-10-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_reservation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='datetime_begin',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
